### ISSUE TITLE
Issue with the url 

### ISSUE THREAD

**Issue by Sevolicious** [pablobiedma/Ticket-SwapMe#14]
I'm new to python. I'm using my buddy chatGPT to run this script. Everything seemed to work. I logged into Facebook and went to the events page on TicketSwap. Though I got this error and this is what chatGPT gave me:

InvalidArgumentException in Selenium: The most critical part of the error message is related to Selenium. It seems the script is trying to navigate to a URL (self.driver.get('insert url here')), but instead of a valid URL, there is placeholder text ('insert url here'). You need to replace 'insert url here' with the actual URL you want the script to navigate to.

Is it possible I need to give the specific url-link on the event in the python script? 
Thanks

**Comment by pablobiedma** [comment]
of course, you need to enter the event link in the python code together with the log in credentials, this should be indicated somewhere in the code
