### ISSUE TITLE
Lots of modifications and things done different, would love to discuss.

### ISSUE THREAD

**Issue by johnneerdael** [pablobiedma/Ticket-SwapMe#7]
I've made my own version and went quite a different route, would love to have a chat and discuss ideas on how things can be done more intelligent in both ways. I use computer vision and a template file to find the captcha buttons and to escape those. Furthermore I made all links independant from the CSS classes since those random strings are changed all the time I noticed and work with a .env file containing the following info (you can use 3 notifiers), I actually haven't tested auto_purchase yet.
[example.env.txt](https://github.com/pablobiedma/TicketSwapMe/files/12268688/example.env.txt)
[ticketswap_bot.py.txt](https://github.com/pablobiedma/TicketSwapMe/files/12268690/ticketswap_bot.py.txt)
![template](https://github.com/pablobiedma/TicketSwapMe/assets/7794406/10a573e7-0012-4dc9-ba27-7d9d04680e37)

Drop me a mail at john@neerdael.nl if you want to discuss ;)

**Comment by wlfeh** [comment]
Hey @johnneerdael, was just looking for a TicketSwap bot and came across your recent comment. Wondering if it works, and, if so, if I could use it? :) I don't have much experience with Python tbh so would appreciate the help. Thanks in advance either way!

**Comment by johnneerdael** [comment]
Otherwise I wouldn't have posted it, it's definitely not perfect yet, but it does work for me, my buddy had issues with identation and a small bug, so without any python you are going to struggle with them unless you have a coding buddy to help (ChatGPT ;)

**Comment by mdb95** [comment]
Hey @johnneerdael: how do you bypass the captcha? I see that you have attached the 'click again' image. Is this image needed by the code? Thanks in advance.

**Comment by mdb95** [comment]
@johnneerdael I notice that I get the following notification: 'Hmm, too many refreshes...
You’ve lost access to this page. You’ll automatically get access again soon – no need to contact us'. Did you also encounter this problem when using your code?

**Comment by johnneerdael** [comment]
Yes friends have same issues, seems for the rest you got it running dandy fine if you get that far. I have some  ideas to work around this and will update when done

**Comment by mdb95** [comment]
In addition: when I use an event that has tickets available, the script does not automatically reserve the tickets, but instead keeps refreshing the event page.

**Comment by johnneerdael** [comment]
[ticketswap_bot.py.v2.txt](https://github.com/pablobiedma/TicketSwapMe/files/12294102/ticketswap_bot.py.v2.txt)

You were completely right and I fixed at least those things ;)

**Comment by hnrxx** [comment]
> [ticketswap_bot.py.v2.txt](https://github.com/pablobiedma/TicketSwapMe/files/12294102/ticketswap_bot.py.v2.txt)
> 
> You were completely right and I fixed at least those things ;)

hi. I ended here because pablo's version didn't worked for me and I tried this last yours. I don't know pretty much about python so I need kind of help if you can :) 

I'm getting this problem on line 46:
> Exception has occurred: OSError
Environment variable xxxxxxxxx@gmail.com is not set
  File "C:\Users\Enrique\Desktop\ticketswap_bot.py.v2.txt", line 46, in validate_env_vars
    raise EnvironmentError(f'Environment variable {var} is not set')
  File "C:\Users\Enrique\Desktop\ticketswap_bot.py.v2.txt", line 21, in __init__
    self.validate_env_vars()
  File "C:\Users\Enrique\Desktop\ticketswap_bot.py.v2.txt", line 316, in main
    bot = TicketSwapBot()
          ^^^^^^^^^^^^^^^
  File "C:\Users\Enrique\Desktop\ticketswap_bot.py.v2.txt", line 326, in <module>
    main()
OSError: Environment variable xxxxxxxxx@gmail.com is not set

**Comment by johnneerdael** [comment]
Hi @hnrxx , this is because you don't have a .env file with your variables set. I'm abandoning this script completely though since yesterday Ticketswap introduced a new raffle system and instead will focus my effort on android automation using adb to pickup notifications automatically for events with a raffle (playing the numbers game by just making sure your in every raffle) or refreshes in app through android automation for tickets without a raffle. It's very unlikely that I would share that code though.

**Comment by BruteS7** [comment]
So it's not possible to use your bot? Or it doesn't work anymore if I got it right? thanks in advance

**Comment by pablobiedma** [comment]
Thank you for submitting this issue @johnneerdael If you want to elecit your changes or have anything specific to discuss please feel free to do so. In the meantime, I'll be sure to close this issue for housekeeping purposes.

**Comment by pablobiedma** [comment]
Thank you for submitting this issue @johnneerdael If you want to elecit your changes or have anything specific to discuss please feel free to do so. In the meantime, I'll be sure to close this issue for housekeeping purposes.
